### ISSUE TITLE
Crear un controller de Ciudades en el proyecto API

### ISSUE THREAD

**Issue by saulroc** [IES-Penas-Negras/ECOTRANS#32]
Crear un controller de ciudades con un evento get que nos devuelva un listado de ciudades.

**Comment by saulroc** [comment]
El controller tiene que instanciar una clase de tipo AccionesCiudad en el constructor
El controller tiene que tener un metodo Get que devuelva el resultado de la accion Listar
El controller tiene que tener un metodo Post que devuelva el resultado de la accion Crear
El controller tiene que tener un metodo Put que devuelva el resultado de la accion Editar
El controller tiene que tener un metodo Delete que devuelva el resultado de la accion Borrar

**Comment by Carlosgv13** [comment]
#32 Finalizado ControllerCiudadesAPI
