### ISSUE TITLE
Crear controller de Objetos en el proyecto API

### ISSUE THREAD

**Issue by saulroc** [IES-Penas-Negras/ECOTRANS#37]
El controller tiene que instanciar una clase de tipo AccionesObjeto en el constructor
El controller tiene que tener un metodo Get que devuelva el resultado de la accion Listar
El controller tiene que tener un metodo Post que devuelva el resultado de la accion Crear
El controller tiene que tener un metodo Put que devuelva el resultado de la accion Editar
El controller tiene que tener un metodo Delete que devuelva el resultado de la accion Borrar

**Comment by alumnoeficiente** [comment]
Creado Controller de Objetos en API

**Comment by alumnoeficiente** [comment]
Falta por hacer el merge y la actualización del Project.
