### ISSUE TITLE
Crear Test para las acciones de Provincias

### ISSUE THREAD

**Issue by saulroc** [IES-Penas-Negras/ECOTRANS#45]
Usar una clase DonacionesTestContext que cargará en memoria creada en #35 
Crear una clase ProvinciasTests, en el constructor crear un nuevo contexto
Crear un objeto de tipo AccionesProvincias y pasarle el contexto creado como parámetro.
Añadir Fact's para la acción de Listar.

**Comment by Carlosgv13** [comment]
#45
