### ISSUE TITLE
Corregir acciones ciudades

### ISSUE THREAD

**Issue by saulroc** [IES-Penas-Negras/ECOTRANS#46]
Corregir las acciones ciudades, 
- Quitar las propiedades que no corresponden con las que tiene el modelo de los request y los response
- Corregir el BorrarCiudadRequest
- Corregir el ListarCiudadResponse
- Corregir los métodos de la clase AccionesCiudades para que utilize el contexto para persistir los datos en la base de datos.

**Comment by alumnoeficiente** [comment]
Tus muertos
________________________________
De: AndreaHC8 ***@***.***>
Enviado: jueves, 2 de junio de 2022 10:56
Para: IES-Penas-Negras/ECOTRANS ***@***.***>
Cc: alumnoeficiente ***@***.***>; Assign ***@***.***>
Asunto: Re: [IES-Penas-Negras/ECOTRANS] Corregir acciones ciudades (Issue #46)


Assigned #46<https://github.com/IES-Penas-Negras/ECOTRANS/issues/46> to @alumnoeficiente<https://github.com/alumnoeficiente>.
