### ISSUE TITLE
Crear modelo Donación

### ISSUE THREAD

**Issue by saulroc** [IES-Penas-Negras/ECOTRANS#7]
Añadir una entidad al modelo del núcleo llamada Donación que tenga las siguientes propiedades:
- Título - texto de 400 caracteres
- Descripción - texto opcional de 3000 caracteres
- Fecha de inicio - Obligatoria
- Fecha de fin - Opcional
- Usuario
- Objetos
- Dirección

**Comment by Carlosgv13** [comment]
#7
