### ISSUE TITLE
Crear acciones objeto

### ISSUE THREAD

**Issue by saulroc** [IES-Penas-Negras/ECOTRANS#9]
Crear una carpeta Acciones en el proyecto Nucleo donde añadir una subcarpeta Objeto, y dentro crear la clase AccionesObjeto.cs, esta clase va a tener los métodos Crear, Listar, Editar y Borrar

**Comment by alumnoeficiente** [comment]
La carpeta se ha creado con éxito, solo queda fusionar la rama asociada a esta tarea a la rama pertinente.
